-------------------------------------------------------------------------------------------------------------------------------
--SELECT SITE_CODE, STORE_NAME, STORE, GRADE, DIVISION, SECTION, DEPARTMENT, ARTICLE_NAME, ATTRIBUTE1, BGT_STR, TABLE_TYPE
--FROM MISRETAIL.T_AUTO_MC_STR;
-------------------------------------------------------------------------------------------------------------------------------
--ZONE IN ('BIHAR-PUJA','EAST','NORTH EAST') --PUJA
--ZONE IN ('NORTH','BIHAR','-') --NON-PUJA
-------------------------------------------------------------------------------------------------------------------------------
SELECT * FROM
(SELECT SITE_CODE, STORE_NAME , STORE_NAME STORE,GRADE, DIVISION, SECTION, DEPARTMENT,ARTICLE_NAME, ATTRIBUTE1,BGT_STR,
DISPLAY_TYPE TABLE_TYPE 
FROM
(SELECT A.*,
CASE WHEN A.STORE_NAME IN('TNS','MHN','CNW','PBS') THEN BGT_STR1+30
WHEN A.STORE_NAME IN('LVP','SPN','DMB','AMB') THEN BGT_STR1+60
WHEN A.STORE_NAME IN('LMN','KMC') THEN BGT_STR1+90
ELSE BGT_STR1 END AS BGT_STR
FROM
(
SELECT A.*,
CASE 
    
     WHEN DIVISION NOT IN ('MENS','LADIES','KIDS','HOME FURNISHING','LIFESTYLE') THEN 60    --GM 60/75 FOR Sep'2025 
    WHEN DIVISION IN ('HOME FURNISHING','LIFESTYLE') THEN 75                               --GM 60/75 FOR Sep'2025    
    
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'OCCASIONAL' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE NOT IN ('BIHAR-PUJA','EAST','NORTH EAST') AND GRADE IN ('C','D','NSO-25')  THEN 90 --NON-PUJA 
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'OCCASIONAL' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE NOT IN ('BIHAR-PUJA','EAST','NORTH EAST') AND GRADE IN ('A','B+','B')  THEN  75    --NON PUJA
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'OCCASIONAL' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE NOT IN ('BIHAR-PUJA','EAST','NORTH EAST') AND GRADE IN ('A+')  THEN  60    --NON PUJA
    
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'OCCASIONAL' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE IN ('BIHAR-PUJA','EAST','NORTH EAST') AND GRADE IN ('D')  THEN 150 --PUJA 
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'OCCASIONAL' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE IN ('BIHAR-PUJA','EAST','NORTH EAST') AND GRADE IN ('A','B+','B','C','NSO-25')  THEN  120    --PUJA
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'OCCASIONAL' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE IN ('BIHAR-PUJA','EAST','NORTH EAST') AND GRADE IN ('A+')  THEN  90    --PUJA
    
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'PREWINTER' AND DIVISION IN ('KIDS','LADIES','MENS') AND GRADE IN('D','NSO-25') THEN 90 --ALL 
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'PREWINTER' AND DIVISION IN ('KIDS','LADIES','MENS') AND GRADE IN('A','B+','B','C') THEN 75 --ALL 
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'PREWINTER' AND DIVISION IN ('KIDS','LADIES','MENS') AND GRADE IN('A+') AND ZONE NOT IN ('BIHAR-PUJA','EAST','NORTH EAST') THEN 60 --NON-PUJA 
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'PREWINTER' AND DIVISION IN ('KIDS','LADIES','MENS') AND GRADE IN('A+') AND ZONE IN ('BIHAR-PUJA','EAST','NORTH EAST') THEN 75 --PUJA 
    
    WHEN DISPLAY_TYPE = 'TABLE' AND ATTRIBUTE1 IN ('PREWINTER','SUMMER','REGULAR') AND DIVISION IN ('KIDS','LADIES','MENS') THEN 90      --PREWINTER/SUMMER/REGULAR TABLE 60
    
    WHEN ATTRIBUTE1 = 'SUMMER' AND DIVISION IN ('KIDS','LADIES','MENS') THEN 90     --SUMMER FLAT 90   
   
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'REGULAR' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE IN ('EAST','NORTH EAST') THEN  90
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'REGULAR' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE NOT IN ('EAST','NORTH EAST') AND GRADE IN ('D','NSO-25') THEN  90
    WHEN DISPLAY_TYPE = 'NON_TABLE' AND ATTRIBUTE1 = 'REGULAR' AND DIVISION IN ('KIDS','LADIES','MENS') AND ZONE NOT IN ('EAST','NORTH EAST') AND GRADE NOT IN ('D','NSO-25') THEN  75
    
    WHEN ATTRIBUTE1 LIKE '%WINTER%' AND DIVISION IN ('KIDS','LADIES','MENS') AND GRADE IN('C','D','NSO-25') THEN  90
    WHEN ATTRIBUTE1 LIKE '%WINTER%' AND DIVISION IN ('KIDS','LADIES','MENS') AND GRADE NOT IN('C','D','NSO-25') THEN  75

    
ELSE 0 END AS BGT_STR1 FROM
(SELECT * FROM
(
(SELECT DISTINCT 
DIVISION, SECTION, DEPARTMENT, ARTICLE_NAME, ATTRIBUTE1,INVITEM_UDFSTRING06 DISPLAY_TYPE
FROM MISRETAIL.ITEM_MV
WHERE DIVISION NOT IN ('FIXED ASSETS','NON-TRADING','DND','RETAIL'))
CROSS JOIN
(SELECT SITE_CODE,STORE_NAME,
OPENING_DATE, STORE_STATUS,  STORE_GRADE,DISTRICT ZONE,
CASE
    WHEN OPENING_DATE = TO_DATE('01-01-00','DD-MM-YY') OR OPENING_DATE >= TO_DATE('01-07-2025','DD-MM-YY')  THEN 'NSO-25'
    ELSE STORE_GRADE END AS GRADE
FROM MISRETAIL.T_STORE_OPENING_DATE
WHERE LOCATION  IN ('STORE')
AND STORE_STATUS IN ('UPCOMING_STORE' ,'ACTIVE')
)
))A)A
ORDER BY SITE_CODE ASC,ATTRIBUTE1,DIVISION,SECTION,DEPARTMENT,ARTICLE_NAME ASC
)A
)